CREATE TABLE COMPANY (
    COMPANY_ID BIGSERIAL,
    TICKER VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (COMPANY_ID),
    UNIQUE(TICKER)
);

CREATE INDEX idx_company_ticker ON company(ticker);